### ISSUE TITLE
Hash of alternative titles

### ISSUE THREAD

**Issue by andrielfn** [andrielfn/tmdb-api#1]
The TMDb provides an ugly hash format of alternatives titles of a movie:

``` ruby
[
 {"iso_3166_1"=>"RU", "title"=>"Город бога"},
 {"iso_3166_1"=>"IT", "title"=>"City of God - La città di Dio"},
 {"iso_3166_1"=>"BR", "title"=>"Cidade de Deus"},
 {"iso_3166_1"=>"FR", "title"=>"La cité de Dieu"},
 {"iso_3166_1"=>"DE", "title"=>"City of God"},
 {"iso_3166_1"=>"CN", "title"=>"上帝之城"},
 {"iso_3166_1"=>"HK", "title"=>"无主之城"},
 {"iso_3166_1"=>"US", "title"=>"City of God"},
 {"iso_3166_1"=>"TW", "title"=>"無法無天"}
]
```

By now, I keep the same pattern in the API wrapper. But, my idea is follow something like this:

``` ruby
[
 {"RU" => "Город бога"},
 {"IT" => "City of God - La città di Dio"},
 {"BR" => "Cidade de Deus"},
 {"FR" => "La cité de Dieu"},
 {"DE" => "City of God"},
 {"CN" => "上帝之城"},
 {"HK" => "无主之城"},
 {"US" => "City of God"},
 {"TW" => "無法無天"},
]
```

What do you think? Is it a good approach?

**Comment by lucasalencar** [comment]
That's a simpler approach than the other one used by the API. But I have one question. What does that code refers to? It's the encoding used on title or used for a specific language?

**Comment by andrielfn** [comment]
No, it's a standard that defines de country codes.
http://en.wikipedia.org/wiki/ISO_3166-1#Current_codes

For example: 
- The Brazil code is **BR**
- The United States code is **US**
- The Argentina codes is **AR**

And so on...

So the API use this standard to refer each country inside de API. I think it's just a pattern and have no utility for the client.

**Comment by lucasalencar** [comment]
Ah, ok. In this case, I think thats better use the simpler way then. It's easier to read and understand.

**Comment by andrielfn** [comment]
:+1: . It's much easier to use the api as well:

``` ruby
alternative_titles.has_key?('BR') # => true
alternative_titles['BR'] # => Cidade de Deus
```

Without the new hash we cannot do this.

**Comment by fernandomantoan** [comment]
Your suggestion is nice... Another point is that we aren't interested about the encoding of the alternative titles... So, getting rid of it is the way to go
