### ISSUE TITLE
TMDb::AlsoKnownAs Error

### ISSUE THREAD

**Issue by Jeehut** [andrielfn/tmdb-api#10]
When using a Person request my Rails app throws this error:

``` ruby
NameError: uninitialized constant TMDb::AlsoKnownAs
```

The reason is (I assume) that I have a model named "Person" in my Rails app as well and Rails mixes things up somehow. But maybe this can be solved within this gem as `TMDb::AlsoKnownAs` is a very strange error, I'm not using the also_known_as field at all (and of course make no call to a class named like that). In the meantime I will think about renaming my class (although 'Person' would be the perfect fit there as well).

Thank you for any help.

**Comment by Jeehut** [comment]
By the way: It didn't help to replace `Person.find(...)` with `TMDb::Person.find(...)`. Still the same issue.

**Comment by andrielfn** [comment]
Hi @Dschee.

Thanks for reporting this issue.

My cue is that the JSON attribute `also_known_as` from the TMDB API is returning as an array of hashes. When this happens, I try to convert these hashes to objects, with the same name as the attribute. This is why the error you reported is uninitialized constant for `AlsoKnownAs`.

I've tried fetch a bunch of people but I couldn't reproduced this error. The attribute `also_known_as` always returns an array of strings.

Could you tell me which Person ID are you using that is throwing this error?

Thanks!

**Comment by Jeehut** [comment]
One persons ID that throws this error is `10980`. I hope that helps. Otherwise I can show you more of my code.

**Comment by Jeehut** [comment]
Also a possible solution might be to make the code that deals with `also_known_as` from the TMDB API more secure and stable. For example it could check all objects it's dealing with for their class type and for nil before using them. I guess the problem here is some malicious data from the TMDb API.

Silently ignoring such data (and optionally logging the issues) from the TMDb API is definitely a better behavior than just throwing an exception / crashing. Especially it is better if one doesn't even use the `also_known_as` field, which is the case for me.

Thank you for your help! :)

**Comment by andrielfn** [comment]
I've fixed this issue with the above commit.

Also, I liked you suggestion and made [this another change](https://github.com/andrielfn/tmdb-api/commit/7dffb1d142e29b12360873c37d80b6816afb7ffe). It will prevent this same exception for unknown attributes, and the attribute will be ignored.

I pushed the version 0.0.8 to Rubygems. Please try it out and let me know if is everything ok.

Thanks for help with that! :smiley:

**Comment by Jeehut** [comment]
v0.0.8 solves the errors for me indeed, thank you @andrielfn! :+1:
