### ISSUE TITLE
Big spec file

### ISSUE THREAD

**Issue by andrielfn** [andrielfn/tmdb-api#2]
If you see, the `movie_spec.rb` file is getting bigger (500LOC so far).

My idea is split this file by each `describe` inside a subdirectory like `spec/tmdb/movies/*`.

Wdyt?

**Comment by fernandomantoan** [comment]
Isn't better to just break the file into multiple files feature-specific?

**Comment by andrielfn** [comment]
@fernandomantoan what you mean with feature-specific?

![screen shot 2013-05-07 at 13 18 10](https://f.cloud.github.com/assets/232190/472417/bf0deef4-b731-11e2-9cef-eceb9ebd4ed6.png)

We have this today. What I meant is to split in another files these describes (`.search`, `.find`, `#images`, ...)
